sudo: false
language: node_js
node_js:
  - 'stable'
branches:
  only:
    - master
notifications:
  webhooks:
    urls:
      - https://stalkr-travis-demo.herokuapp.com
      - https://travis-temp.herokuapp.com
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
